const usStates = [
    { name: "Alabama", abbr: "AL", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Alaska", abbr: "AK", tz: "America/Anchorage", tzName: "Alaska Time" },
    { name: "Arizona", abbr: "AZ", tz: "America/Phoenix", tzName: "Mountain Time (No DST)" },
    { name: "Arkansas", abbr: "AR", tz: "America/Chicago", tzName: "Central Time" },
    { name: "California", abbr: "CA", tz: "America/Los_Angeles", tzName: "Pacific Time" },
    { name: "Colorado", abbr: "CO", tz: "America/Denver", tzName: "Mountain Time" },
    { name: "Connecticut", abbr: "CT", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Delaware", abbr: "DE", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Florida", abbr: "FL", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Georgia", abbr: "GA", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Hawaii", abbr: "HI", tz: "Pacific/Honolulu", tzName: "Hawaii-Aleutian Time" },
    { name: "Idaho", abbr: "ID", tz: "America/Boise", tzName: "Mountain Time" },
    { name: "Illinois", abbr: "IL", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Indiana", abbr: "IN", tz: "America/Indiana/Indianapolis", tzName: "Eastern Time" },
    { name: "Iowa", abbr: "IA", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Kansas", abbr: "KS", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Kentucky", abbr: "KY", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Louisiana", abbr: "LA", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Maine", abbr: "ME", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Maryland", abbr: "MD", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Massachusetts", abbr: "MA", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Michigan", abbr: "MI", tz: "America/Detroit", tzName: "Eastern Time" },
    { name: "Minnesota", abbr: "MN", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Mississippi", abbr: "MS", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Missouri", abbr: "MO", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Montana", abbr: "MT", tz: "America/Denver", tzName: "Mountain Time" },
    { name: "Nebraska", abbr: "NE", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Nevada", abbr: "NV", tz: "America/Los_Angeles", tzName: "Pacific Time" },
    { name: "New Hampshire", abbr: "NH", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "New Jersey", abbr: "NJ", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "New Mexico", abbr: "NM", tz: "America/Denver", tzName: "Mountain Time" },
    { name: "New York", abbr: "NY", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "North Carolina", abbr: "NC", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "North Dakota", abbr: "ND", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Ohio", abbr: "OH", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Oklahoma", abbr: "OK", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Oregon", abbr: "OR", tz: "America/Los_Angeles", tzName: "Pacific Time" },
    { name: "Pennsylvania", abbr: "PA", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Rhode Island", abbr: "RI", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "South Carolina", abbr: "SC", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "South Dakota", abbr: "SD", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Tennessee", abbr: "TN", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Texas", abbr: "TX", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Utah", abbr: "UT", tz: "America/Denver", tzName: "Mountain Time" },
    { name: "Vermont", abbr: "VT", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Virginia", abbr: "VA", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Washington", abbr: "WA", tz: "America/Los_Angeles", tzName: "Pacific Time" },
    { name: "West Virginia", abbr: "WV", tz: "America/New_York", tzName: "Eastern Time" },
    { name: "Wisconsin", abbr: "WI", tz: "America/Chicago", tzName: "Central Time" },
    { name: "Wyoming", abbr: "WY", tz: "America/Denver", tzName: "Mountain Time" }
];